# Numpy Operations

In [1]:
import numpy as np
from math import sqrt

In [2]:
a = np.array([1, 2 ,3])
b = np.array([5, 6 ,7])

In [3]:
# numpy arrays perform element wise operations
a+2

array([3, 4, 5])

In [4]:
# arrays of same size can be added
a+b

array([ 6,  8, 10])

In [5]:
print(a*b)

[ 5 12 21]


In [6]:
print(a**2)

[1 4 9]


In [7]:
print(a.mean())
print(a.sum())

2.0
6


### Numpy methods make calculations easy for us.
*E.g.* - to find euclidian distance between 2 points we can the formuls √[1->n∑(xi-yi)**2]

In [8]:
# let a and b be 2 points and d be the distance
a = np.array([1,2,3])
b = np.array([5,6,7])
dsq = ((a-b)**2).sum()
d = sqrt(dsq)
d

6.928203230275509

In [9]:
a1 = np.array([[1,2], [3,4]])
a2 = np.array([[10,20], [30,40]])

# taking dotproduct of vectors
a1.dot(a2)

array([[ 70, 100],
       [150, 220]])

In [10]:
np.random.seed(2)

In [11]:
np.random.rand(3)

array([0.4359949 , 0.02592623, 0.54966248])

In [12]:
np.random.seed(2)

In [13]:
np.random.rand(3)

array([0.4359949 , 0.02592623, 0.54966248])