# In this module we will learn about numpy module.
NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [7]:
import numpy as np

#### Convert python list to numpy array

In [8]:
l = [1, 2 ,3]
np.array(l)

array([1, 2, 3])

#### Create arrays with initial vlues

In [9]:
# zeroes function initialize the array with 0 value of the provided data type
# syntax = np.zeroes(size, data_type)
a =np.zeros(10, int)
print(a)
a.dtype

[0 0 0 0 0 0 0 0 0 0]


dtype('int64')

#### Create an array of nore than one dimension
to create an array of more than one dimension provide a tuple instead of an integer.
E.g. to create a 2D array  - np.zeroes((rows, cols))

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

##### Unlike python lists, you can only have values of same data type in a numpy arrays.

In [11]:
# it converted "1" to integer 1
a[0] = "1"
a

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# values which cannot be converted will throw an error
a[1] = "b"

ValueError: invalid literal for int() with base 10: 'b'

In [12]:
b = np.zeros((2, 3, 2))
b

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
# to access data
b[0][1][1]

0.0

In [14]:
# slicing
print(a)
a[2:4]

[1 0 0 0 0 0 0 0 0 0]


array([0, 0])

In [15]:
print(b.shape)
a = np.array([[1,2,3], [4,5,6], [1,2,3], [4,5,6]])
a[0]
a[:, 2:4]

(2, 3, 2)


array([[3],
       [6],
       [3],
       [6]])